/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_typesprovider_test
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "test_types_provider.pl", "sysRules.pl","ctx_typesprovider_test"
	)
}

