/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_rpi
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "test_messages.pl", "sysRules.pl","ctx_rpi"
	)
}

