/* Generated by AN DISI Unibo */ 
package it.unibo.testalarmreceiver

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Testalarmreceiver ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("[TestAlarmReceiver] Started.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_idle") { //this:State
					action { //it:State
						println("[TestAlarmReceiver] Idle.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="state_handle",cond=whenEvent("stop"))
					transition(edgeName="t01",targetState="state_handle",cond=whenEvent("resume"))
				}	 
				state("state_handle") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stop(_)"), Term.createTerm("stop"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("[TestAlarmReceiver] Received stop.")
						}
						if( checkMsgContent( Term.createTerm("resume(_)"), Term.createTerm("resume"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("[TestAlarmReceiver] Received resume.")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
			}
		}
}
