/* Generated by AN DISI Unibo */ 
package it.unibo.ctxmapwithobstqak22
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "mapwithobstqak22.pl", "sysRules.pl","ctxmapwithobstqak22"
	)
}

