/* Generated by AN DISI Unibo */ 
package it.unibo.led_test

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led_test ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("[LedTest] Started.")
						wasteservice.raspberry.led.ledSupportBCR.createLed(  )
						CoapObserverSupport(myself, "localhost","11802","ctx_raspberrypi","faketrolley")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_idle") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="state_handle",cond=whenDispatch("coapUpdate"))
				}	 
				state("state_handle") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val TTState = wasteservice.TransportTrolleyState.parseFromMessage(payloadArg(1))  
								 wasteservice.raspberry.led.ledSupportBCR.doLed(TTState)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_off") { //this:State
					action { //it:State
						 wasteservice.raspberry.led.ledSupportBCR.doLed(wasteservice.TransportTrolleyState.HOME)  
						println("[LedTest] Led OFF.")
						delay(3000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_on", cond=doswitch() )
				}	 
				state("state_on") { //this:State
					action { //it:State
						 wasteservice.raspberry.led.ledSupportBCR.doLed(wasteservice.TransportTrolleyState.STOPPED)  
						println("[LedTest] Led ON.")
						delay(3000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_blink", cond=doswitch() )
				}	 
				state("state_blink") { //this:State
					action { //it:State
						 wasteservice.raspberry.led.ledSupportBCR.doLed(wasteservice.TransportTrolleyState.MOVING)  
						println("[LedTest] Led BLINKING.")
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_off", cond=doswitch() )
				}	 
			}
		}
}
