/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_ledstate_test
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "test_led_state.pl", "sysRules.pl","ctx_ledstate_test"
	)
}

