/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_stopresume_test
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "test_stop_resume.pl", "sysRules.pl","ctx_stopresume_test"
	)
}

