/* Generated by AN DISI Unibo */ 
package it.unibo.alarm_handler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Alarm_handler ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var SonarDistance: Double = Double.MAX_VALUE
				var PrevAlarm: Boolean = false
				var Alarm: Boolean = false
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("[AlarmHandler] Started.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_idle") { //this:State
					action { //it:State
						println("[AlarmHandler] Listening for sonar events...")
						 PrevAlarm = Alarm  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="state_handle_sonar_distance",cond=whenDispatch("sonardistance"))
				}	 
				state("state_handle_sonar_distance") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("sonardistance(DISTANCE)"), Term.createTerm("sonarevent(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Alarm = wasteservice.Utils.isAlarm(payloadArg(0))  
								println("[AlarmHandler] Received sonar event: ${payloadArg(0)}")
								if(  Alarm != PrevAlarm  
								 ){if(  Alarm == true  
								 ){emit("stop", "stop(_)" ) 
								}
								else
								 {emit("resume", "resume(_)" ) 
								 }
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
			}
		}
}
