/* Generated by AN DISI Unibo */ 
package it.unibo.textdisplay_bcr

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Textdisplay_bcr ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var TTState: wasteservice.TransportTrolleyState = wasteservice.TransportTrolleyState.HOME
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("[TextDisplayBCR] Started.")
						wasteservice.raspberry.display.displaySupportBCR.createTextDisplay(  )
						wasteservice.raspberry.display.displaySupportBCR.doDisplay( "", "TT: ${TTState.name}"  )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_idle") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="state_handle",cond=whenEvent("trolley_state_changed"))
				}	 
				state("state_handle") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("trolley_state_changed(STATE)"), Term.createTerm("trolley_state_changed(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val TTState = wasteservice.TransportTrolleyState.parseFromMessage(payloadArg(0))
												wasteservice.raspberry.display.displaySupportBCR.doDisplay("", "TT: ${TTState.name}")
								println("[TextDisplayBCR] State: $TTState")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
			}
		}
}
