/* Generated by AN DISI Unibo */ 
package it.unibo.mapperqak22

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Mapperqak22 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 var NumStep   = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("mapperbuilder starts")
						 unibo.kotlin.planner22Util.initAI()  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doAheadMove", cond=doswitch() )
				}	 
				state("doAheadMove") { //this:State
					action { //it:State
						delay(300) 
						request("step", "step(350)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="continue",cond=whenReply("stepdone"))
					transition(edgeName="t01",targetState="turn",cond=whenReply("stepfail"))
				}	 
				state("continue") { //this:State
					action { //it:State
						 unibo.kotlin.planner22Util.updateMap(  "w", "" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doAheadMove", cond=doswitch() )
				}	 
				state("turn") { //this:State
					action { //it:State
						 NumStep = NumStep + 1  
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						  unibo.kotlin.planner22Util.updateMap(  "l", "" ) 
									unibo.kotlin.planner22Util.showMap()		 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doAheadMove", cond=doswitchGuarded({ NumStep < 4  
					}) )
					transition( edgeName="goto",targetState="endwork", cond=doswitchGuarded({! ( NumStep < 4  
					) }) )
				}	 
				state("endwork") { //this:State
					action { //it:State
						 	unibo.kotlin.planner22Util.showMap();
						 			unibo.kotlin.planner22Util.saveRoomMap("mapRoomEmpty");
						println("mapperbuilder BYE")
						terminate(1)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
