/* Generated by AN DISI Unibo */ 
package it.unibo.display_test

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Display_test ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var TTState: wasteservice.TransportTrolleyState = wasteservice.TransportTrolleyState.HOME
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("[TextDisplayTest] Started.")
						wasteservice.raspberry.display.displaySupportBCR.createTextDisplay(  )
						CoapObserverSupport(myself, "localhost","11802","ctx_raspberrypi","faketrolley")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_idle") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="state_handle",cond=whenDispatch("coapUpdate"))
				}	 
				state("state_handle") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  wasteservice.TransportTrolleyState.parseFromMessage(payloadArg(1)) != TTState  
								 ){ TTState = wasteservice.TransportTrolleyState.parseFromMessage(payloadArg(1))  
								 wasteservice.raspberry.display.displaySupportBCR.doDisplay("", "TT: ${TTState.name}")  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
			}
		}
}
