/* Generated by AN DISI Unibo */ 
package it.unibo.pathobs

import alice.tuprolog.Term
import it.unibo.kactor.ActorBasicFsm
import it.unibo.kactor.CoapObserverSupport
import it.unibo.kactor.MsgUtil
import it.unibo.kactor.Transition
import kotlinx.coroutines.CoroutineScope

class Pathobs ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CoapObserverSupport(myself, "localhost","8020","ctxbasicrobot","pathexec")
					}
					 transition(edgeName="t014",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 MsgUtil.outgreen("applobserver OBSERVES: ${payloadArg(1)} FROM ${payloadArg(0)} ")  
						}
					}
					 transition(edgeName="t015",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
			}
		}
}
