/* Generated by AN DISI Unibo */ 
package it.unibo.faketrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Faketrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("[TransportTrolley] Started.")
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_home", cond=doswitch() )
				}	 
				state("state_home") { //this:State
					action { //it:State
						println("[TransportTrolley] HOME.")
						updateResourceRep( "transporttrolley(HOME)"  
						)
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_moving", cond=doswitch() )
				}	 
				state("state_moving") { //this:State
					action { //it:State
						println("[TransportTrolley] MOVING.")
						updateResourceRep( "transporttrolley(MOVING)"  
						)
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_stopped", cond=doswitch() )
				}	 
				state("state_stopped") { //this:State
					action { //it:State
						println("[TransportTrolley] STOPPED.")
						updateResourceRep( "transporttrolley(STOPPED)"  
						)
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_home", cond=doswitch() )
				}	 
			}
		}
}
