/* Generated by AN DISI Unibo */ 
package it.unibo.wasteservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wasteservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("[WasteService] Initializing...")
					}
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_idle") { //this:State
					action { //it:State
					}
					 transition(edgeName="t00",targetState="state_handle_store",cond=whenRequest("storerequest"))
					transition(edgeName="t01",targetState="state_handle_distance",cond=whenDispatch("distance"))
				}	 
				state("state_handle_store") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("storerequest(wasteType,truckLoad)"), Term.createTerm("storerequest(TYPE,WEIGHT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  /*enough space*/  
								 ){answer("storerequest", "loadaccepted", "loadaccepted(_)"   )  
								forward("doDeposit", "doDeposit(TYPE,WEIGHT)" ,"transporttrolley" ) 
								}
								else
								 {answer("storerequest", "loadrejected", "loadaccepted(_)"   )  
								 }
								forward("updategui", "updategui(_)" ,"wasteservicestatusgui" ) 
						}
						delay(1000) 
					}
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
				state("state_handle_distance") { //this:State
					action { //it:State
						if(  payloadArg(0) >= wasteservice.Constants.DLIMT  
						 ){forward("stop", "stop(_)" ,"transporttrolley" ) 
						}
						else
						 {forward("resume", "resume(_)" ,"transporttrolley" ) 
						 }
					}
					 transition( edgeName="goto",targetState="state_idle", cond=doswitch() )
				}	 
			}
		}
}
