/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_test_storerequest
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "test_storerequest.pl", "sysRules.pl","ctx_test_storerequest"
	)
}

