/* Generated by AN DISI Unibo */ 
package it.unibo.smartdevice_simulator

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Smartdevice_simulator ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var Types: String = ""
				var TypesList = arrayListOf<wasteservice.WasteType>()
				
				var WasteType: wasteservice.WasteType = wasteservice.WasteType.PLASTIC
				var WasteWeight: Double = 10.0
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						println("[SmartDevice Simulator] Started")
						discardMessages = false
						delay(5000) 
						request("storerequest", "storerequest($WasteType,$WasteWeight)" ,"wasteservice" )  
						println("[SmartDevice Simulator] Sent storerequest($WasteType, $WasteWeight)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t20",targetState="state_handle_loadaccepted",cond=whenReply("loadaccepted"))
					transition(edgeName="t21",targetState="state_handle_loadrejected",cond=whenReply("loadrejected"))
				}	 
				state("state_handle_loadaccepted") { //this:State
					action { //it:State
						println("[SmartDevice Simulator] Received LoadAccepted")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("state_handle_loadrejected") { //this:State
					action { //it:State
						println("[SmartDevice Simulator] Received LoadRejected")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
