/* Generated by AN DISI Unibo */ 
package it.unibo.ctxPathexecutor
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "test_echo_waste_server.pl", "sysRules.pl","ctxPathexecutor"
	)
}

