/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_defects_solution_test
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "test_defects_solution.pl", "sysRules.pl","ctx_defects_solution_test"
	)
}

